### ISSUE TITLE
A new option for the `response_format` parameter

### ISSUE THREAD

**Issue by Lambdua** [Lambdua/openai4j#54]
developers can now supply a JSON Schema via json_schema, a new option for the response_format parameter.

https://openai.com/index/introducing-structured-outputs-in-the-api

**Comment by bertilmuth** [comment]
Just to be sure: this hasn't been implemented yet, right? Are you looking for community support?

It would be nice to be able to generate JSON schemas on the fly, as shown in the introduction to [structured outputs](https://platform.openai.com/docs/guides/structured-outputs/introduction) with the `CalendarEvent ` object, rather than being forced to specify the JSON schema yourself.

**Comment by Lambdua** [comment]
A new version is expected to be released this month. If possible, please feel free to submit your MQ. Thank you

**Comment by bertilmuth** [comment]
I will provide a pull request soon.

**Comment by Lambdua** [comment]
Thank you, a new version will be released soon
